### ISSUE TITLE
Start ice bath

### ISSUE THREAD

**Issue by danodemano** [bmedicke/anova.py#2]
Any idea if it's possible to start the ice bath using the API?

**Comment by nockstarr** [comment]
Doesn't seems like the author have implemented that. However should be easy to implement if you know what the payload should be..

**Comment by danodemano** [comment]
That would be the rub, right?  How would I be able to find that out?

**Comment by danodemano** [comment]
Hmmm...so these are the two jobs.  First is when it's checking the temp.  Second it when the ice bath is monitoring.  EDIT: There appear to be 3 stages actually.  Not sure what the difference between the first and second is.  Different job_type but same job_stage.  Third is for sure as it's just watching the temp.

`{"status":{"cooker_id":"anova xxxxxxxxxxxxxx","firmware_version":"ver 6.1.1","is_running":true,"current_temp":34,"target_temp":75,"temp_unit":"f","speaker_mode":true,"current_job_id":"96143761-f105-4106-975b-00519d1d22d7","current_job":{"job_id":"96143761-f105-4106-975b-00519d1d22d7","job_type":"ice_bath_test","job_stage":"checking_temperature","is_running":true,"target_temp":75,"temp_unit":"f","job_start_time":"2019-02-20T23:49:49.118071Z","job_update_time":"2019-02-20T23:49:59.118073Z","max_circulation_interval":300,"threshold_temp":40,"job_info":{"display_item_identifier":"1550706591184","duration":0,"job_type":"ice_bath_test","source":"3","temperature":0,"temperature_unit":"f"}},"is_timer_running":false}}`


`{"status":{"cooker_id":"anova xxxxxxxxxxxxxx","firmware_version":"ver 6.1.1","is_running":true,"current_temp":34.3,"target_temp":75,"temp_unit":"f","speaker_mode":true,"current_job_id":"b6d136d2-9964-4b4c-88b3-1e4a2132cbb2","current_job":{"job_id":"b6d136d2-9964-4b4c-88b3-1e4a2132cbb2","job_type":"temperature_monitor","job_stage":"checking_temperature","is_running":true,"target_temp":75,"temp_unit":"f","job_start_time":"2019-02-20T23:50:01.717988Z","job_update_time":"2019-02-20T23:50:11.717989Z","max_circulation_interval":300,"threshold_temp":40,"job_info":{"display_item_identifier":"1550706603795","duration":0,"job_type":"temperature_monitor","source":"3","temperature":0,"temperature_unit":"f"}},"is_timer_running":false}}`

`{"status":{"cooker_id":"anova xxxxxxxxxxxxxx","firmware_version":"ver 6.1.1","is_running":false,"current_temp":33.7,"target_temp":75,"temp_unit":"f","speaker_mode":false,"current_job_id":"b6d136d2-9964-4b4c-88b3-1e4a2132cbb2","current_job":{"job_id":"b6d136d2-9964-4b4c-88b3-1e4a2132cbb2","job_type":"temperature_monitor","job_stage":"monitoring","is_running":true,"target_temp":75,"temp_unit":"f","job_start_time":"2019-02-20T23:50:01.717988Z","job_update_time":"2019-02-20T23:55:11.722876Z","max_circulation_interval":300,"threshold_temp":40,"job_info":{"display_item_identifier":"1550706603795","duration":0,"job_type":"temperature_monitor","source":"3","temperature":0,"temperature_unit":"f"}},"is_timer_running":false}}`

**Comment by danodemano** [comment]
I have created #3 to address this.  On a side note, there is another method to get the secret and ID by using a packet capture utility on Android.  This works regardless of certificate pinning (and is how I was able to get the proper commands for the ice bath).

**Comment by bmedicke** [comment]
Thank you for the pull request, it looks great. I'll test it over the weekend.
